name: Test Docker build

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4
  
      - id: compose
        name: Compose
        run: docker compose build

